apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-for-strava
  namespace: strava-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-for-strava
  template:
    metadata:
      labels:
        app: stats-for-strava
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

      initContainers:
        - name: fix-cache-permissions
          image: busybox:1.35
          command: ['sh', '-c', 'chown -R 1000:1000 /var/www/var/cache || true']

      containers:
        - name: statistics-for-strava
          image: robiningelbrecht/strava-statistics:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 8080
          env:
            - name: STRAVA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: strava-credentials
                  key: client-id
            - name: STRAVA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: strava-credentials
                  key: client-secret
            - name: STRAVA_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: strava-credentials
                  key: refresh-token
            - name: TZ
              value: "Europe/Oslo"
            - name: CADDY_LOG_LEVEL
              value: "DEBUG"
          volumeMounts:
            - name: strava-pvc
              mountPath: /var/www/storage
              subPath: storage
            - name: strava-pvc
              mountPath: /var/www/build
              subPath: build
            - name: conf
              mountPath: /var/www/config/app/config.yaml
              subPath: config.yaml

      volumes:
        - name: strava-pvc
          persistentVolumeClaim:
            claimName: strava-data-pvc
        - name: conf
          configMap:
            name: strava-general-config

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: strava-daily-update
  namespace: strava-stats
spec:
  schedule: "15 4 * * *"               # 04:15 every day
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2

  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

          initContainers:
            - name: fix-cache-permissions
              image: busybox:1.35
              command: ['sh', '-c', 'chown -R 1000:1000 /var/www/var/cache || true']

          restartPolicy: OnFailure

          containers:
            - name: daily-update
              image: robiningelbrecht/strava-statistics:latest
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 300m
                  memory: 512Mi
                limits:
                  cpu: 500m
                  memory: 768Mi
              envFrom:
                - secretRef:
                    name: strava-credentials
              env:
                - name: TZ
                  value: "Europe/Oslo"
              command:
                - sh
                - -c
                - |
                  bin/console app:strava:import-data && \
                  bin/console app:strava:build-files
              volumeMounts:
                - name: strava-pvc
                  mountPath: /var/www/storage
                  subPath: storage
                - name: strava-pvc
                  mountPath: /var/www/build
                  subPath: build
                - name: conf
                  mountPath: /var/www/config/app/config.yaml
                  subPath: config.yaml

          volumes:
            - name: strava-pvc
              persistentVolumeClaim:
                claimName: strava-data-pvc
            - name: conf
              configMap:
                name: strava-general-config
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strava-data-pvc
  namespace: strava-stats
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: strava-general-config
  namespace: strava-stats
data:
  config.yaml: |
    general:
      appUrl: "https://sfs.gunhildsbu.no/"
      appSubTitle: mikkel-stats
      profilePictureUrl: https://dgalywyr863hv.cloudfront.net/pictures/athletes/101757310/24662245/2/large.jpg
      athlete:
        birthday: "2000-05-25"
        maxHeartRateFormula: fox
      appearance:
        locale: en_US
        unitSystem: metric
        timeFormat: 24
        dateFormat:
          short: d-m-y
          normal: d-m-Y
      import:
        numberOfNewActivitiesToProcessPerImport: 100

---

apiVersion: v1
kind: Service
metadata:
  name: strava-service
  namespace: strava-stats
spec:
  selector:
    app: stats-for-strava
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP


--- 

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-strava
  namespace: strava-stats
spec:
  parentRefs:
    - name: gateway
      namespace: envoy
  hostnames:
    - sfs.gunhildsbu.no
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: strava-service
      namespace: strava-stats
      port: 80

---