apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-for-strava
  namespace: strava-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-for-strava
  template:
    metadata:
      labels:
        app: stats-for-strava
    spec:
      # No securityContext - run as root to write to /var/www/public/manifest.json
      initContainers:
        - name: init-storage
          image: busybox:1.35
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
              mkdir -p /data/storage/database /data/storage/files /data/storage/gear-maintenance /data/build
              chown -R 1000:1000 /data
              chmod -R 775 /data
          volumeMounts:
            - name: strava-pvc
              mountPath: /data

      containers:
        - name: statistics-for-strava
          image: robiningelbrecht/strava-statistics:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 8080
          env:
            - name: STRAVA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: strava-credentials
                  key: client-id
            - name: STRAVA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: strava-credentials
                  key: client-secret
            - name: STRAVA_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: strava-credentials
                  key: refresh-token
            - name: TZ
              value: "Europe/Oslo"
            - name: CADDY_LOG_LEVEL
              value: "DEBUG"
          volumeMounts:
            - name: strava-pvc
              mountPath: /var/www/storage/database
              subPath: storage/database
            - name: strava-pvc
              mountPath: /var/www/storage/files
              subPath: storage/files
            - name: strava-pvc
              mountPath: /var/www/storage/gear-maintenance
              subPath: storage/gear-maintenance
            - name: strava-pvc
              mountPath: /var/www/build
              subPath: build
            - name: cache-volume
              mountPath: /var/www/var/cache
            - name: conf
              mountPath: /var/www/config/app
              readOnly: true

      volumes:
        - name: strava-pvc
          persistentVolumeClaim:
            claimName: strava-data-pvc
        - name: cache-volume
          emptyDir: {}
        - name: conf
          configMap:
            name: strava-general-config

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: strava-daily-update
  namespace: strava-stats
spec:
  schedule: "15 4 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2

  jobTemplate:
    spec:
      template:
        spec:
          # No securityContext - run as root to write to /var/www/public/manifest.json
          nodeSelector:
            role: control-plane
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
          restartPolicy: OnFailure

          containers:
            - name: daily-update
              image: robiningelbrecht/strava-statistics:latest
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 300m
                  memory: 512Mi
                limits:
                  cpu: 500m
                  memory: 768Mi
              env:
                - name: STRAVA_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: strava-credentials
                      key: client-id
                - name: STRAVA_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: strava-credentials
                      key: client-secret
                - name: STRAVA_REFRESH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: strava-credentials
                      key: refresh-token
                - name: TZ
                  value: "Europe/Oslo"
              command:
                - sh
                - -c
                - |
                  bin/console app:strava:import-data
                  bin/console app:strava:build-files
              volumeMounts:
                - name: strava-pvc
                  mountPath: /var/www/storage/database
                  subPath: storage/database
                - name: strava-pvc
                  mountPath: /var/www/storage/files
                  subPath: storage/files
                - name: strava-pvc
                  mountPath: /var/www/storage/gear-maintenance
                  subPath: storage/gear-maintenance
                - name: strava-pvc
                  mountPath: /var/www/build
                  subPath: build
                - name: conf
                  mountPath: /var/www/config/app
                  readOnly: true

          volumes:
            - name: strava-pvc
              persistentVolumeClaim:
                claimName: strava-data-pvc
            - name: conf
              configMap:
                name: strava-general-config

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strava-data-pvc
  namespace: strava-stats
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: strava-general-config
  namespace: strava-stats
data:
  config.yaml: |
    general:
      appUrl: 'https://sfs.gunhildsbu.no/'
      appSubTitle: mikkel-stats
      profilePictureUrl: https://dgalywyr863hv.cloudfront.net/pictures/athletes/101757310/24662245/2/large.jpg
      athlete:
        birthday: '2000-05-25'
        maxHeartRateFormula: 'fox'
        heartRateZones:
          mode: relative
          default:
            zone1:
              from: 50
              to: 60
            zone2:
              from: 61
              to: 70
            zone3:
              from: 71
              to: 80
            zone4:
              from: 81
              to: 90
            zone5:
              from: 91
              to: null
        weightHistory:
          "2000-05-25": 70
        ftpHistory:
          cycling: []
          running: []

    appearance:
      locale: 'en_US'
      unitSystem: 'metric'
      timeFormat: 24
      dateFormat:
        short: 'd-m-y'
        normal: 'd-m-Y'
      dashboard:
        layout: null
      heatmap:
        polylineColor: '#fc6719'
        tileLayerUrl: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
        enableGreyScale: true
      photos:
        hidePhotosForSportTypes: []
        defaultEnabledFilters:
          sportTypes: []
          countryCode: null
      sportTypesSortingOrder: []

    import:
      numberOfNewActivitiesToProcessPerImport: 250
      sportTypesToImport: []
      activityVisibilitiesToImport: []
      skipActivitiesRecordedBefore: null
      activitiesToSkipDuringImport: []
      optInToSegmentDetailImport: false

    metrics:
      eddington:
        - label: 'Ride'
          showInNavBar: true
          showInDashboardWidget: true
          sportTypesToInclude: ['Ride', 'MountainBikeRide', 'GravelRide', 'VirtualRide']
        - label: 'Run'
          showInNavBar: true
          showInDashboardWidget: true
          sportTypesToInclude: ['Run', 'TrailRun', 'VirtualRun']
        - label: 'Walk'
          showInNavBar: false
          showInDashboardWidget: false
          sportTypesToInclude: ['Walk', 'Hike']

    gear:
      stravaGear: []
      customGear: []

    zwift:
      level: null
      racingScore: null

    integrations:
      notifications:
        services: []
      ai:
        enabled: false
        enableUI: false
        provider: 'openAI'
        configuration:
          key: ''
          model: ''
          url: ''

    daemon:
      cron:
        - action: 'importDataAndBuildApp'
          expression: '0 14 * * *'
          enabled: false
        - action: 'gearMaintenanceNotification'
          expression: '0 14 * * *'
          enabled: false
        - action: 'appUpdateAvailableNotification'
          expression: '0 14 * * *'
          enabled: false

---

apiVersion: v1
kind: Service
metadata:
  name: strava-service
  namespace: strava-stats
spec:
  selector:
    app: stats-for-strava
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-strava
  namespace: strava-stats
spec:
  parentRefs:
    - name: gateway
      namespace: envoy
  hostnames:
    - sfs.gunhildsbu.no
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: strava-service
          namespace: strava-stats
          port: 80