apiVersion: v1
kind: Secret
metadata:
  name: vivi-strava-credentials
  namespace: vivi-strava
type: Opaque
stringData:
  client-id: "197823"
  client-secret: "c4d05360b0bece2dbec4646911b7df411257e04f"
  refresh-token: ""
